MciaPorCaducar/WebMvc/MciaPorCaducar/Controllers/MciaPorCaducarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMvc.Menu;

namespace WebMvc.MciaPorCaducar.Controllers
{
    public class MciaPorCaducarController : Controller
    {
        NGMciaPorCaducarSorianaTienda.NGTerminalPortatil.NGTerminalPortatil ng = new NGMciaPorCaducarSorianaTienda.NGTerminalPortatil.NGTerminalPortatil();

        // GET: MciaPorCaducar
        public ActionResult Index()
        {
            return View();
        }

        #region Captura de Mercancia
        [CheckSessionOut]
        public ActionResult CapturaMcia()
        {
            try
            {
                Session["flagOpcion"] = string.Empty;

                System.Data.DataSet fol = ng.CaducaEntrada();
                /*********************
                 * Fol_MciaCaduca
                   --------------
                   324
                 *********************/

                if (fol != null)
                {
                    if (fol.Tables.Count > 0)
                    {
                        foreach (System.Data.DataRow rowfol in fol.Tables[0].Rows)
                        {
                            Session["FolMcia"] = rowfol[0].ToString().Trim();
                        }
                        Session["flagOpcion"] = "Principal";
                        Session["TituloPagina"] = "2.-Captura Mcía Caduc";
                        Session["flagField"] = "inArt";
                    }
                }
                else
                {
                    Session["flagOpcion"] = "Error";
                    Session["lblResult"] = "ERROR: NO EXISTE".ToLower();
                }

                return View();
            }
            catch (Exception ex)
            {
                Session["flagOpcion"] = "Error";
                if (ex.Message.Contains("Int32") || ex.Message.Contains("Error converting data type to decimal"))
                {
                    Session["lblResult"] = "NO EXISTE, DATO INVALIDO".ToLower();
                }
                else if (ex.Message.Contains("Object reference not set to an instance") || ex.Message.Contains("Referencia a objeto no establecida"))
                {
                    Session["lblResult"] = "NO SE PUDO REALIZAR LA ACCION".ToLower();
                }
                else
                {
                    Session["lblResult"] = ex.Message.ToLower();
                }

                if (Session["flagOpcion"].ToString() == "" || Session["flagOpcion"].ToString() == "Error")
                {
                    return RedirectToAction("Inicio", "Menu");
                }

                return View();
            }
        }

        [CheckSessionOut]
        public ActionResult mCapturaMcia()
        {
            try
            {
                Session["flagOpcion"] = string.Empty;

                System.Data.DataSet fol = ng.CaducaEntrada();
                /*********************
                 * Fol_MciaCaduca
                   --------------
                   324
                 *********************/

                if (fol != null)
                {
                    if (fol.Tables.Count > 0)
                    {
                        foreach (System.Data.DataRow rowfol in fol.Tables[0].Rows)
                        {
                            Session["FolMcia"] = rowfol[0].ToString().Trim();
                        }
                        Session["flagOpcion"] = "Principal";
                        Session["TituloPagina"] = "2.-Captura Mcía Caduc";
                        Session["flagField"] = "inArt";
                    }
                }
                else
                {
                    Session["flagOpcion"] = "Error";
                    Session["lblResult"] = "ERROR: NO EXISTE".ToLower();
                }

                return View();
            }
            catch (Exception ex)
            {
                Session["flagOpcion"] = "Error";
                if (ex.Message.Contains("Int32") || ex.Message.Contains("Error converting data type to decimal"))
                {
                    Session["lblResult"] = "NO EXISTE, DATO INVALIDO".ToLower();
                }
                else if (ex.Message.Contains("Object reference not set to an instance") || ex.Message.Contains("Referencia a objeto no establecida"))
                {
                    Session["lblResult"] = "NO SE PUDO REALIZAR LA ACCION".ToLower();
                }
                else
                {
                    Session["lblResult"] = ex.Message.ToLower();
                }

                if (Session["flagOpcion"].ToString() == "" || Session["flagOpcion"].ToString() == "Error")
                {
                    return RedirectToAction("Index", "Menu");
                }

                return View();
            }
        }

        [AuthorizationPrivilegeFilter]
        public ActionResult CaducaArticulo(string inArt)
        {
            string temp = Request.QueryString["userName"] + "Controller";

            try
            {
                System.Data.DataSet cadArt = ng.CaducaArticulo(Session["FolMcia"].ToString(), inArt);

                if (cadArt != null)
                {
                    if (cadArt.Tables.Count > 0)
                    {
                        foreach (System.Data.DataRow rowcadArt in cadArt.Tables[0].Rows)
                        {
                            Session["NumSKU"] = rowcadArt[0].ToString().Trim();
                            temp = "Continuar~" + rowcadArt[1].ToString().Trim().ToLower();
                        }
                        //Pantalla 2 
                    }
                }
                else
                {
                    temp = "Error~" + "ERROR: NO EXISTE".ToLower();
                }
            }
            catch (Exception ex)
            {
                string msjError;
                if (ex.Message.Contains("Int32") || ex.Message.Contains("Error converting data type to decimal"))
                {
                    msjError = "NO EXISTE, DATO INVALIDO".ToLower();
                }
                else if (ex.Message.Contains("Object reference not set to an instance") || ex.Message.Contains("Referencia a objeto no establecida"))
                {
                    msjError = "ERROR: NO SE PUDO REALIZAR LA ACCION".ToLower();
                }
                else
                {
                    msjError = ex.Message.ToLower();
                }

                temp = "Error~" + msjError;
            }

            return Json(temp, JsonRequestBehavior.AllowGet);
        }

        [AuthorizationPrivilegeFilter]
        public ActionResult CaducaLote(string inLot)
        {
            string temp = Request.QueryString["userName"] + "Controller";

            try
            {
                System.Data.DataSet cadLot = ng.CaducaLote(Session["FolMcia"].ToString(), Session["NumSKU"].ToString(), inLot);

                if (cadLot != null)
                {
                    if (cadLot.Tables.Count > 0)
                    {
                        foreach (System.Data.DataRow rowcadLot in cadLot.Tables[0].Rows)
                        {
                            temp = "Continuar~" + rowcadLot[2].ToString().Trim() + ";";
                            //BitExisteLote
                            if (rowcadLot[0].ToString().Trim() == "0")
                            {
                                //Pantalla 4
                                temp += "FecCad";
                            }
                            else
                            {
                                //Pantalla 3
                                temp += "LoteReg;" + rowcadLot[1].ToString().Trim();
                            }
                        }
                    }
                }
                else
                {
                    temp = "Error~" + "ERROR: NO EXISTE".ToLower();
                }
            }
            catch (Exception ex)
            {
                string msjError;
                if (ex.Message.Contains("Int32") || ex.Message.Contains("Error converting data type to decimal"))
                {
                    msjError = "NO EXISTE, DATO INVALIDO".ToLower();
                }
                else if (ex.Message.Contains("Object reference not set to an instance") || ex.Message.Contains("Referencia a objeto no establecida"))
                {
                    msjError = "ERROR: NO SE PUDO REALIZAR LA ACCION".ToLower();
                }
                else
                {
                    msjError = ex.Message.ToLower();
                }

                temp = "Error~" + msjError;
            }

            return Json(temp, JsonRequestBehavior.AllowGet);
        }

        [AuthorizationPrivilegeFilter]
        public ActionResult CaducaFecCaducidad(string inLot, string inFec)
        {
            string temp = Request.QueryString["userName"] + "Controller";

            try
            {
                System.Data.DataSet fecCad = ng.CaducaFecCaducidad(Session["FolMcia"].ToString(), Session["NumSKU"].ToString(), inLot, inFec);

                if (fecCad != null)
                {
                    if (fecCad.Tables.Count > 0)
                    {
                        foreach (System.Data.DataRow rowfecCad in fecCad.Tables[0].Rows)
                        {
                            Session["BitFechaDif"] = rowfecCad[1].ToString().Trim();

                            //BitFechaPasada
                            if (rowfecCad[0].ToString().Trim() == "1")
                            {
                                //Pantalla 5  
                                temp = "Continuar~ConservaFec";
                            }
                            //BitFechaDif 
                            else if (rowfecCad[1].ToString().Trim() == "1")
                            {

MciaPorCaducar/WebMvc/MciaPorCaducar/Views/AutorizaMerma.cshtml
@{
    Layout = "~/Shared/Views/_LayoutOperaViews.cshtml";
}

<form id="formAutorizaMerma" class="form" action="@Url.Action("AutorizaMerma", "MciaPorCaducar")" method="get">
    <div id="Error" style="display:none;color:white;">
        <p class="groove">
            <label id="ErrorMsjs"></label>
            @Session["lblResult"]
            <br />
            <input id="btnOk" type="button" class="btn btn-default btn-sm" style="width: 50%" onkeypress="myFuncionOK()" onclick="myFuncionOK()" value="OK" />
        </p>
    </div>

    @*Pantalla 1*@
    <div id="Principal" style="display:none">
        <table>
            <tr>
                <td colspan="2"><label>Jefe Dpto:</label></td>
            </tr>
            <tr>
                <td colspan="2">
                    @if (Session["cmb_JEFE"] != null)
                    {
                        @Html.DropDownList("cmb_JEFE", (SelectList)Session["cmb_JEFE"], new { @listplaceholder = "Seleccione", @onkeypress = "KeyPressed('cmb_JEFE','','formAutorizaMerma')", @onchange = "KeyPressed('cmb_JEFE','','formAutorizaMerma')", @style = "width: 200px;" })
                    }
                </td>
            </tr>
        </table>
        <p class="pFol">Para salir de la opción haz clic <label class="folNvo" onclick="KeyPressed('cmb_JEFE', '', 'formAutorizaMerma')">aqui.</label></p>
    </div>

    @*Pantalla 2*@
    <div id="CapArt" style="display:none">
        <table>
            <tr>
                <td><label>Jefe Dpto:</label></td>
                <td><label class="textCapitalize" id="NomJefe" name="NomJefe"></label></td>
            </tr>
            <tr>
                <td colspan="2"><label>Articulo:</label></td>
            </tr>
            <tr><td colspan="2"><input type="text" id="inArt" name="inArt" onkeyup="KeyPressed('inArt','','formAutorizaMerma')" onkeypress="return soloNumeros(event)" class="inputCodigo" placeholder="12344553" aria-describedby="sizing-addon3"></td></tr>

        </table>

    </div>

    @*Pantalla 3*@
    <div id="ModCant" style="display:none">
        <table>
            <tr>
                <td colspan="2">
                    <label>El Articulo con el Número de Lote, ya fue Registrado con una Cant de </label>
                    <label id="CantArt"></label>
                    <label> piezas.</label>
                </td>
            </tr>
            <tr>
                <td colspan="2"><label>Desea Modificar la Cantidad?</label></td>
            </tr>
        </table>
        <div class="panel panel-success">
            <div class="panel-heading">
                <label class="panel-title">1.-SI    2.-NO</label>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-4">
                        <label>Opción</label>
                        <input type="text" id="op" name="op" maxlength="1" onfocus="posicion(this);" onkeyup="KeyPressed('op','','formAutorizaMerma')" onkeypress="return soloOpciones(event)" placeholder="Selecciona una opción" aria-describedby="basic-addon1" />
                    </div>
                </div>
            </div>
        </div>
    </div>

    @*Pantalla 4*@
    <div id="CapCantMerma" style="display:none">

        <table>
            <tr>
                <td><label>Jefe Dpto:</label></td>
                <td><label class="textCapitalize" name="NomJefe"></label></td>
            </tr>
            <tr>
                <td colspan="2"><label>Articulo:</label></td>
            </tr>
            <tr><td colspan="2"><label class="textCapitalize" id="DesArt"></label></td></tr>
            <tr>
                <td><label>Lote:</label></td>
                <td><label id="Lote"></label></td>
            </tr>
            <tr>
                <td><label>Fec Cad:</label></td>
                <td><label id="Fecha"></label></td>
            </tr>
            <tr>
                <td><label>Exist:</label></td>
                <td><label id="Existe"></label></td>
            </tr>
            <tr><td colspan="2">Cantidad a Mermar:</td></tr>
            <tr><td colspan="2"><input type="text" id="inCan" name="inCan" onkeyup="KeyPressed('inCan','','formAutorizaMerma')" onkeypress="return soloDecimal(event,this)" placeholder="12344553" aria-describedby="sizing-addon3"></td></tr>
        </table>

    </div>

    @*Pantalla 5*@
    <div id="GenActa" style="display:none">

        <table>
            <tr>
                <td colspan="2"><label>Se han Registrado Códigos para Merma</label></td>
            </tr>
            <tr>
                <td colspan="2"><label>Desea Generar el Acta de Destrucción?</label></td>
            </tr>
        </table>
        <div class="panel panel-success">
            <div class="panel-heading">
                <label class="panel-title">1.-SI    2.-NO</label>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-4">
                        <label>Opción</label>
                        <input type="text" id="op2" name="op2" maxlength="1" onfocus="posicion(this);" onkeyup="KeyPressed('op2','','formAutorizaMerma')" onkeypress="return soloOpciones(event)" placeholder="Selecciona una opción" aria-describedby="basic-addon1" />
                    </div>
                </div>
            </div>
        </div>

    </div>

    @*Pantalla 6*@
    <div id="FolGen" style="display:none">

        <table>
            <tr>
                <td colspan="2">
                    <label>El Folio de Acta de Destrucción Asignado es el </label>
                    <label id="NumActaDestruccion"></label>
                    <label> con Fecha </label>
                    <label id="FechaSKU"></label>
                </td>
            </tr>
        </table>
        <div class="panel panel-success">
            <div class="panel-heading">
                <label class="panel-title">1.-CONTINUAR</label>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-4">
                        <label>Opción</label>
                        <input type="text" id="op3" name="op3" maxlength="1" onfocus="posicion(this);" onkeyup="KeyPressed('op3','','formAutorizaMerma')" onkeypress="return soloOpcionUnica(event)" placeholder="Selecciona una opción" aria-describedby="basic-addon1" />
                    </div>
                </div>
            </div>
        </div>
    </div>


    @*Pantalla 7*@
    <div id="NoGen" style="display:none">
        <table>
            <tr>
                <td colspan="2"><label>No se Generó Folio de Acta Destrucción</label></td>
            </tr>
        </table>
        <div class="panel panel-success">
            <div class="panel-heading">
                <label class="panel-title">1.-CONTINUAR</label>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-4">
                        <label>Opción</label>
                        <input type="text" id="op4" name="op4" maxlength="1" onfocus="posicion(this);" onkeyup="KeyPressed('op4','','formAutorizaMerma')" onkeypress="return soloOpcionUnica(event)" placeholder="Selecciona una opción" aria-describedby="basic-addon1" />
                    </div>
                </div>
            </div>
        </div>
    </div>

    <a href="#" id="B" onclick="CheckFocus();return false;" style="text-decoration:none;color:#ffffff;"></a>

    <input type="hidden" id="FocusOn" name="FocusOn" value="@Session["flagField"]" />
    <input id="flagOpcion" value="@Session["flagOpcion"]" style="visibility:hidden" />
    <input id="flagError" value="@Session["flagError"]" style="visibility:hidden" />
    <input id="flagEsc" type="text" name="flagEsc" style="visibility:hidden" />
</form>

<script>

    function funFolNvo(opcion) {
        switch (opcion) {
            case "MenuInicio":
                document.getElementById("flagEsc").value = "Esc";
                document.getElementById("formAutorizaMerma").submit();
                break;
        }
    }


</script>

MciaPorCaducar/WebMvc/MciaPorCaducar/Views/CapturaMcia.cshtml
@{
    Layout = "~/Shared/Views/_LayoutOperaViews.cshtml";
}

<form id="formCapturaMcia" class="form" action="@Url.Action("CapturaMcia", "MciaPorCaducar")" method="get">
    <div id="Error" style="display:none;color:white;">
        <p class="groove">
            <label id="ErrorMsjs"></label>
            @Session["lblResult"]
            <br />
            <input id="btnOk" type="button" class="btn btn-default btn-sm" style="width: 50%" onkeypress="myFuncionOK()" onclick="myFuncionOK()" value="OK" />
        </p>
    </div>

    @*Pantalla 1*@
    <div id="Principal" style="display:none">

        <table>
            <tr>
                <td><label>Folio:</label></td>
                <td><label id="FolMcia">@Session["FolMcia"]</label></td>
            </tr>
            <tr>
                <td colspan="2"><label>Articulo:</label></td>
            </tr>
            <tr><td colspan="2"><input type="text" id="inArt" name="inArt" onkeyup="KeyPressed('inArt','','formCapturaMcia')" onkeypress="return soloDecimal(event, this)" class="inputCodigo" placeholder="12344553" aria-describedby="sizing-addon3"></td></tr>
        </table>

    </div>

    @*Pantalla 2*@
    <div id="Lote" style="display:none">
        <table>
            <tr>
                <td><label>Folio:</label></td>
                <td><label>@Session["FolMcia"]</label></td>
            </tr>
            <tr>
                <td colspan="2"><label>Articulo:</label></td>
            </tr>
            <tr><td colspan="2"><label class="textCapitalize" name="DescCod" id="DescCod"></label></td></tr>
            <tr>
                <td colspan="2"><label>Lote:</label></td>
            </tr>
            <tr><td colspan="2"><input type="text" id="inLot" name="inLot" onkeyup="KeyPressed('inLot','','formCapturaMcia')" placeholder="12344553" aria-describedby="sizing-addon3" /></td></tr>
        </table>
    </div>

    @*Pantalla 3*@
    <div id="LoteReg" style="display:none">
        <table>
            <tr>
                <td colspan="2">
                    <label>El Articulo con el Número de Lote ya fue Registrado con una Cantidad de </label>
                    <label id="CanCap"></label>
                    <label> Piezas ¿Desea Modificar la Cant?</label>
                </td>
            </tr>
        </table>
        <div class="panel panel-success">
            <div class="panel-heading">
                <label class="panel-title">1.-SI    2.-NO</label>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-4">
                        <label>Opción</label>
                        <input type="text" id="op" name="op" maxlength="1" onfocus="posicion(this);" onkeyup="KeyPressed('op','','formCapturaMcia')" onkeypress="return soloOpciones(event)" placeholder="Selecciona una opción" aria-describedby="basic-addon1" />
                    </div>
                </div>
            </div>
        </div>
    </div>

    @*Pantalla 4*@
    <div id="FecCad" style="display:none">
        <table>
            <tr>
                <td><label>Folio:</label></td>
                <td><label>@Session["FolMcia"]</label></td>
            </tr>
            <tr>
                <td colspan="2"><label>Articulo:</label></td>
            </tr>
            <tr><td colspan="2"><label class="textCapitalize" name="DescCod"></label></td></tr>
            <tr>
                <td><label>Lote:</label></td>
                <td><label id="lblLote" name="lblLote"></label></td>
            </tr>
            <tr>
                <td colspan="2"><label>Fecha Caducidad:</label></td>
            </tr>
            <tr>
                <td colspan="2"> <label>(AAAAMMDD)</label></td>
            </tr>
            <tr><td colspan="2"><input type="text" id="inFec" name="inFec" maxlength="8" onkeyup="KeyPressed('inFec','','formCapturaMcia')" onkeypress="return soloNumeros(event)" placeholder="12344553" aria-describedby="sizing-addon3"></td></tr>
        </table>
    </div>

    @*Pantalla 5*@
    <div id="ConservaFec" style="display:none">
        <table>
            <tr>
                <td colspan="2"><label>La Fecha de Cad es una Fecha Pasada.</label></td>
            </tr>
            <tr>
                <td colspan="2"><label>Desea Conservar esa Fecha?</label></td>
            </tr>
        </table>
        <div class="panel panel-success">
            <div class="panel-heading">
                <label class="panel-title">1.-SI    2.-NO</label>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-4">
                        <label>Opción</label>
                        <input type="text" id="op2" name="op2" maxlength="1" onfocus="posicion(this);" onkeyup="KeyPressed('op2','','formCapturaMcia')" onkeypress="return soloOpciones(event)" placeholder="Selecciona una opción" aria-describedby="basic-addon1" />
                    </div>
                </div>
            </div>
        </div>
    </div>

    @*Pantalla 6*@
    <div id="CoincideFec" style="display:none">
        <table>
            <tr>
                <td colspan="2"><label>La Fecha de Cad No coincide con el Sistema.</label></td>
            </tr>
            <tr>
                <td colspan="2"><label>Desea Conservar esa Fecha?</label></td>
            </tr>
        </table>
        <div class="panel panel-success">
            <div class="panel-heading">
                <label class="panel-title">1.-SI    2.-NO</label>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-4">
                        <label>Opción</label>
                        <input type="text" id="op3" name="op3" maxlength="1" onfocus="posicion(this);" onkeyup="KeyPressed('op3','','formCapturaMcia')" onkeypress="return soloOpciones(event)" placeholder="Selecciona una opción" aria-describedby="basic-addon1" />
                    </div>
                </div>
            </div>
        </div>
    </div>

    @*Pantalla 7*@
    <div id="CapturaCant" style="display:none">
        <table>
            <tr>
                <td><label>Folio:</label></td>
                <td><label>@Session["FolMcia"]</label></td>
            </tr>
            <tr>
                <td colspan="2"><label>Articulo:</label></td>
            </tr>
            <tr><td colspan="2"><label class="textCapitalize" name="DescCod"></label></td></tr>
            <tr>
                <td><label>Lote:</label></td>
                <td><label name="lblLote"></label></td>
            </tr>
            <tr>
                <td><label>Fec Cad:</label></td>
                <td><label id="FechaCad"></label></td>
            </tr>
            <tr>
                <td><label>Cant:</label></td>
                <td><input type="text" id="inCan" name="inCan" onkeyup="KeyPressed('inCan','','formCapturaMcia')" onkeypress="return soloNumeros(event)" placeholder="12344553" aria-describedby="sizing-addon3" /></td>
            </tr>
        </table>

    </div>

    @*Pantalla 8*@
    <div id="NoCerrado" style="display:none">
        <table>
            <tr>
                <td colspan="2"><label>El Folio @Session["FolMcia"] No Ha Sido Cerrado</label></td>
            </tr>
            <tr><td colspan="2"><label>Desea Cerrar el Folio de Captura?</label></td></tr>
        </table>
        <div class="panel panel-success">
            <div class="panel-heading">
                <label class="panel-title">1.-SI    2.-NO</label>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-4">
                        <label>Opción</label>
                        <input type="text" id="op4" name="op4" maxlength="1" onfocus="posicion(this);" onkeyup="KeyPressed('op4','','formCapturaMcia')" onkeypress="return soloOpciones(event)" placeholder="Selecciona una opción" aria-describedby="basic-addon1" />
                    </div>
                </div>
            </div>
        </div>
    </div>


    <a href="#" id="B" onclick="CheckFocus();return false;" style="text-decoration:none;color:#ffffff;"></a>

    <input type="hidden" id="FocusOn" name="FocusOn" value="@Session["flagField"]" />
    <input id="flagOpcion" value="@Session["flagOpcion"]" style="visibility:hidden" />
    <input id="flagError" value="@Session["flagError"]" style="visibility:hidden" />
</form>

<script>

  
</script>